### ISSUE TITLE
better alternative to writing and batch and bash scripts

### ISSUE THREAD

**Issue by dangmoody** [dangmoody/HLML#54]
Every time I need a script I have to write it twice: Once for Batch, and again for Bash.  This is annoying and not that easy to maintain.  I need a better solution.

I was looking at ODIN recently, could be good?

**Comment by Yann4** [comment]
Looks like all of your scripts are build scripts, or build script-adjacent - why not use make?

**Comment by dangmoody** [comment]
Great idea @Yann4 

@Flave229 has agreed to look at this along with his dedicated VS solution work.

**Comment by dangmoody** [comment]
This is now all working.

We still use a batch file for running the MSVC side of things, but given that's Windows only I'm totally happy with that.
