### ISSUE TITLE
Compilation errors in VS 2022

### ISSUE THREAD

**Issue by bonorumetmalorum** [dangmoody/HLML#57]
Trying to compile in a cpp project on visual studio 2022 tool chain results in the following two errors:

- Error C3861 'assert': identifier not found in bool2.inl:69
- Error C4146 unary minus operator applied to unsigned type, result still unsigned in hlml_functions_vector.h:2409	

Error c3861 is easily solved by including assert.h at the top of hlml.h. C4146 can be fixed by removing the "-" from the return types of negation operator functions.

**Comment by dangmoody** [comment]
On it.

**Comment by dangmoody** [comment]
First bug fixed in a789bde.

Second bug fixed in 45023ef.

I'll close this when the release containing the fixes goes live.

**Comment by dangmoody** [comment]
Fixed in v2.1.0
